all: espressif-esp32-gcc espressif-esp32-binutils

espressif-esp32-gcc: FORCE
	@printf "\033[0;31m  UNPACKING\033[0m %s\n" $@
	$(Q)make -C $@

espressif-esp32-binutils: FORCE
	@printf "\033[0;31m  UNPACKING\033[0m %s\n" $@
	$(Q)make -C $@

FORCE:

