all: build-gcc-install.tar.gz 
	tar xfvz build-gcc-install.tar.gz

build-gcc-install.tar.gz:
	wget --no-check-certificate "https://onedrive.live.com/download?cid=17DB6531C8EE4D20&resid=17DB6531C8EE4D20%21341&authkey=AD-tC3A7IEJZsF8&download=1" -O build-gcc-install.tar.gz

clean: 
	rm -rf build-gcc-install/
	rm build-gcc-install.tar.gz

